# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7f3a90a2d9d77fee53db85eebeadf73130936a4a9137631135b6b1d1996c955f1184c1a8b57c7346a14767e9ff69ccd0f16723a18eb47866053c960fc8f66f9

test:
  secret_key_base: f2667b511300bdd5be8dab80336adb8b9d6a12261a4ce984279c7fcdd03b9bb7aa119bb2ae8fde37402db80d007730e7501dd325448a98e0db2adb9e1e033861

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
